version: '3'

services:
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  flask:
    build: web/
    volumes:
      - /drunner_db_sqlite:/db
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB=/db/drunner.sqlite.db
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
  mailer:
    build: worker/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /drunner_db_sqlite:/db
    environment:
      - DB=/db/drunner.sqlite.db
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis

volumes:
  drunner_db_sqlite: